### ISSUE TITLE
Bug in v2.0

### ISSUE THREAD

**Issue by ResonanceLau** [mobfox/MobFox-iOS-SDK-Core-Lib#15]
When I loaded an interstitial ad in iOS9.2, I encountered the following bug,

**MobFox SDK (MobFoxAd - loadAd) Exception: +[UIDevice isIpad]: unrecognized selector sent to class**

**Comment by shimisheetrit** [comment]
Please set Other Linker Flags to -all_load. this appears under Project Definitions.

'Project Definitions
Select project target and under Build Settings setup Other Linker Flags to -all_load.'
