### ISSUE TITLE
Disable Location Services For Interstitial AD

### ISSUE THREAD

**Issue by kokteyldev** [mobfox/MobFox-iOS-SDK-Core-Lib#18]
Is it possible to add a method like locationServicesDisabled to disable location services for interstital ads.

**Comment by nabriski** [comment]
Hi,
The interstitial object uses a standard ad internally so you can do:

``` objective-c
[interstitial.ad locationServicesDisabled:YES];
```

Is this what you're looking for?

**Comment by kokteyldev** [comment]
Yes, I am looking for something similar but as far as I understand +locationServicesDisabled is a static method and not available via instance variable interstitial.ad. 
Below you can find how do I implement this feature in native and banner ads, and I am looking for an equivalent for interstitial ads.

self.mobFoxAdView = [[MobFoxAd alloc] init:adUnitID withFrame:adRect];
[MobFoxAd locationServicesDisabled:YES];

self.nativeAd = [[MobFoxNativeAd alloc] init:adUnitID ];
[MobFoxNativeAd locationServicesDisabled:YES];

**Comment by nabriski** [comment]
you are correct, I think that if you call `[MobFoxAd locationServicesDisabled:YES];` this will work for the interstitial as well.
But don't close this issue as we'll add this method to the interstitial formally on our next release.

**Comment by kokteyldev** [comment]
Thank you @nabriski, we are planning to release an new version of our game this week , it would be great if you could add this feature this week.

**Comment by nabriski** [comment]
ok, you'll be notified when I close this issue

**Comment by nabriski** [comment]
Hi, just updated with this fix.
