### ISSUE TITLE
[MobFoxNativeAd locationServicesDisabled:YES];

### ISSUE THREAD

**Issue by kokteyldev** [mobfox/MobFox-iOS-SDK-Core-Lib#20]
Is there any chance that this method is not disableing locationServices? Below you can find our implementation and we are seeing location permission dialog in our app.

```
                self.nativeAd = [[MobFoxNativeAd alloc] init:adUnitID];
                [MobFoxNativeAd locationServicesDisabled:YES];
                self.nativeAd.delegate = self;
                [self.nativeAd loadAd];
```

**Comment by shimisheetrit** [comment]
Declare locationServicesDisabled: before init:

[MobFoxNativeAd locationServicesDisabled:YES];
self.nativeAd = [[MobFoxNativeAd alloc] init:adUnitID];
self.nativeAd.delegate = self;
[self.nativeAd loadAd];

**Comment by kokteyldev** [comment]
Hi, we implemented interstitial as below but your sdk asks for location permission for interstitial ad. Can you please check?

```
[MobFoxInterstitialAd locationServicesDisabled:YES];
_interstitial = [[MobFoxInterstitialAd alloc] init:self.placement.adspaceId
                            withRootViewController:[UIApplication sharedApplication].keyWindow.rootViewController];
_interstitial.delegate = self;
[_interstitial loadAd];
```

**Comment by shimisheetrit** [comment]
Have you declared it with No value in other declaration for disabling location services?
Location services functionality should be set (disabled) with Yes value for all ad declarations.

**Comment by kokteyldev** [comment]
No I haven't. I have 3 kinds of banner declarations in my project, none of them have locationServicesDisabled call with NO parameter.

[MobFoxAd locationServicesDisabled:YES];

```
dispatch_async( dispatch_get_main_queue(), ^(void){
    _banner = [[MobFoxAd alloc] init:self.placement.adspaceId withFrame:CGRectMake(0, 0, self.placement.bannerWidth, bannerHeight)];
    _banner.delegate = self;
    [_banner loadAd];
});

dispatch_async(dispatch_get_main_queue(), ^{
    [MobFoxNativeAd locationServicesDisabled:YES];
    _nativeBanner = [[MobFoxNativeAd alloc] init:self.placement.adspaceId];
    _nativeBanner.delegate = self;
    [_nativeBanner loadAd];
});

[MobFoxInterstitialAd locationServicesDisabled:YES];
_interstitial = [[MobFoxInterstitialAd alloc] init:self.placement.adspaceId
                            withRootViewController:[UIApplication sharedApplication].keyWindow.rootViewController];
_interstitial.delegate = self;
[_interstitial loadAd];
```

**Comment by shimisheetrit** [comment]
Add [MobFoxAd locationServicesDisabled:YES]; to the the first declaration:

dispatch_async( dispatch_get_main_queue(), ^(void){
   [MobFoxAd locationServicesDisabled:YES];
    _banner = [[MobFoxAd alloc] init:self.placement.adspaceId withFrame:CGRectMake(0, 0, self.placement.bannerWidth, bannerHeight)];
    _banner.delegate = self;
    [_banner loadAd];
});
