### ISSUE TITLE
dyld: Symbol not found: __swift_getInitializedObjCClass

### ISSUE THREAD

**Issue by scano** [mobfox/MobFox-iOS-SDK-Core-Lib#21]
Just following the instructions from the main page, we are unable to integrate the lastest version of the SDK in an Objective-C proyect.
- We drag the `MobFoxSDKCore.embeddedframework` in project
- We sure that the `MobFoxSDKCore.framkework` is in Embedded Binaries

The complete error message:

```
dyld: Symbol not found: __swift_getInitializedObjCClass
  Referenced from: /Users/AAA/Library/Developer/CoreSimulator/Devices/835593D6-2157-43CC-968F-31BC16C8726A/data/Containers/Bundle/Application/8F5A58DA-B5C0-4E4F-B5DE-1AFCC1379CEA/MyApp.app/Frameworks/MobFoxSDKCore.framework/MobFoxSDKCore
  Expected in: /Users/AAA/Library/Developer/CoreSimulator/Devices/835593D6-2157-43CC-968F-31BC16C8726A/data/Containers/Bundle/Application/8F5A58DA-B5C0-4E4F-B5DE-1AFCC1379CEA/MyApp.app/Frameworks/libswiftCore.dylib
 in /Users/AAA/Library/Developer/CoreSimulator/Devices/835593D6-2157-43CC-968F-31BC16C8726A/data/Containers/Bundle/Application/8F5A58DA-B5C0-4E4F-B5DE-1AFCC1379CEA/MyApp.app/Frameworks/MobFoxSDKCore.framework/MobFoxSDKCore
```

Deploy Target: 8.3
XCode: 7.3

Also, the demo app not work and the Pod still install 2.1.9 version.

Thanks,

**Comment by nabriski** [comment]
Thanks, we will fix this as soon as possible.

**Comment by shimisheetrit** [comment]
Our product includes Swift source files, even if your app doesn't use Swift you need to enable embedding Swift code. to resolve it set 'Embedded Content Contains Swift Code' to Yes.
Now it's also mentioned in docs. regarding to the second issue, now it should install the latest version v2.2.2.

**Comment by scano** [comment]
Yes, we set the flag on the config but same error. Just drag the latest version on proyect, added to `Embedded Binaries`, set the flags but the app crash just before appear. If we remove the SDK, everything works fine.

We try to test your DemoApp (Objective-c) fixing the path of the MobFox SDK with the same result.

We have no idea how to fix it.
I have attached some screenshots.
![setup-1](https://cloud.githubusercontent.com/assets/6553243/17129929/40172122-5316-11e6-8a2d-48806433d088.jpg)
![setup-2](https://cloud.githubusercontent.com/assets/6553243/17129930/44029b22-5316-11e6-8cef-bbf4f6c741d8.jpg)
![setup-3](https://cloud.githubusercontent.com/assets/6553243/17129936/46d3879e-5316-11e6-9a07-3a8e743fa2b8.jpg)

**Comment by scano** [comment]
Just found the problem:

Xcode set `Enable Bitcode` to `Yes` by default. 
So I drag the `MobFoxSDKCoreDynamicBitCode` SDK and change the import to `<MobFoxSDKCoreDynamicBitCode/MobFoxSDKCore.h>` and looks like everything works fine.

Thanks for your time and patience.

**Comment by nabriski** [comment]
Guess we better make the BitCode version the default

**Comment by gylippus** [comment]
@scano have you tried to Archive?

I'm not 100% sure that forcing Bitcode is a positive solution. Once you Enable Bitcode, every framework needs to be using it. In our case, `GoogleMobileAds.framework` does not, so we are not able to submit a new build until we either figure out if there is a version of that with Bitcode supported, or a different way to use the non-bitcode version of this library. I assume that `GoogleMobileAds.framework` won't be the only framework we use that is going to give this error. 

From Apple: "Note: For iOS apps, bitcode is the default, but optional. For watchOS and tvOS apps, bitcode is required. If you provide bitcode, all apps and frameworks in the app bundle (all targets in the project) need to include bitcode."

@shimisheetrit is it possible to continue looking for a solution to the original issue here?

**Comment by gylippus** [comment]
@shimisheetrit I just updated to the very latest SDK and it is possible you fixed the original issue here because the non-bitcode SDK seems to be working better now. Did you all make a change?

**Comment by shimisheetrit** [comment]
I did some changes but they are not related to Bitcode. as you can see I changed the names of directories and files, and the default lib enabling Bitcode.

**Comment by shimisheetrit** [comment]
Anyway it's related to the functionality of Bitcode

**Comment by shimisheetrit** [comment]
not related I meant.

**Comment by scano** [comment]
@gylippus I don't try to Archive. The problem comes about the `Bitcode` param is enabled by default. Just dragged the `Bitcode` version of the SDK and works like a charm. I attached an screenshot of a new standard iOS project created with Xcode 7.3.1

![settings](https://cloud.githubusercontent.com/assets/6553243/17147170/ddcb9470-5361-11e6-9ed1-781dae1e2834.jpg)

I'm using others SDK's like Smaato or MMedia without any problem with this param.
I think that this threat is good to advice other developers about this param.

In any case, thanks for your patience and for letting me know about the `Bitcode` param.
(Sorry for my poor english)

**Comment by scano** [comment]
Hi team, just updated to new MobFoxSDKCore 2.2.4.

When run the app appear this warning but works fine:
`/Volumes/Data/Works-iOS/MyApp/<module-includes>:1:1: Umbrella header for module 'MobFoxSDKCore' does not include header 'WKWebViewJavascriptBridge.h'`

When I try to archive the project this error appear:

`ld: bitcode bundle could not be generated because '/Volumes/Data/Works-iOS/MyApp/MyApp/-AdsFrameworks/MobFoxSDKCore.embeddedframework/MobFoxSDKCore.framework/MobFoxSDKCore(MobFoxNativeCustomEvent.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

The same error apper with 2.2.1
I drag the new `MobFoxSDKCore.embeddedframework`
Bitcode is enabled.

Let me know if you need more info about the integration.

**Comment by shimisheetrit** [comment]
I succeeded to reproduce the error you received, it happens because of the declaration of Bitcode with 'Yes' value. but we know that you want to support Bitcode in your project and we'll provide very soon a new version which includes static library with Bitcode enabled, and the same for dynamic library.

**Comment by shimisheetrit** [comment]
New version 2.2.5 has been released, it includes static lib with bitcode enabled. please try it and let us know if it works.

**Comment by scano** [comment]
Just tested with Bitcode enabled and disabled and works fine.
I can Archive the project without any issue.

Only appears a warning with this message:
`<module-includes>:1:1: Umbrella header for module 'MobFoxSDKCore' does not include header 'WKWebViewJavascriptBridge.h'`

But the app works fine.
Thanks.
